version: '1.0'

services:
  server:
    image: 'server'
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 8000:8000
  client:
    image: 'client'
    build:
      context: ./client
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - 3000:3000